matrix:
    include:
        - language: rust
          script: cargo test
        - language: node_js
          node_js:
              - 7
              - 8
              - 9
          before_script: cd js
