matrix:
    include:
        - language: rust
          script: cargo test
        - language: node_js
          node_js:
              - 9
              - 10
          before_script: cd js/pkg && npm test
