[package]
name = "parser-rs-wasm"
version = "0.1.0"
authors = ["Stan Rozenraukh <stan@stanistan.com>"]
build = "build.rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[build-dependencies]
peg = { version = "0.5" }
